[project]
name = "use_your_head"
version = "0.1.0"
description = "Package for solving Tetris-like puzzles"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
